### ISSUE TITLE
Is this project related to the smil2css library?

### ISSUE THREAD

**Issue by Emasoft** [prateekjadhwani/svg2css#4]
Is this project related to the popular smil2css library? It seems to do something similar to that one.
https://github.com/webframes/smil2css

**Comment by prateekjadhwani** [comment]
I believe SMIL2CSS returns an SVG file in response with css animation in its style. So it converts an animated SVG to SVG with CSS animations. You can get more idea of what I am talking about here in this link https://css-tricks.com/guide-svg-animations-smil/
SVG2CSS requires an SVG path as an input for the animation property itself. So your SVG input is only the behavior input of how the animation should work. More details can be found here https://github.com/prateekjadhwani/svg2css/blob/master/TUTORIAL.md

Also the overall output is css and not a full fledged SVG file which makes it different from SMIL2CSS. So technically the two projects are for two different purposes.
